// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALD42778h4_m0Kyy0ocUeeWO7krtZyS1A',
    appId: '1:813403601538:web:fd825cce77ec63045b929b',
    messagingSenderId: '813403601538',
    projectId: 'shawan-app',
    authDomain: 'shawan-app.firebaseapp.com',
    storageBucket: 'shawan-app.firebasestorage.app',
    measurementId: 'G-XNN20TLRM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLjykoTSCzf9QkvEaxSlBTsxJGIjdDGA',
    appId: '1:813403601538:android:3b60d8916fb4d5085b929b',
    messagingSenderId: '813403601538',
    projectId: 'shawan-app',
    storageBucket: 'shawan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fP6ucKQs2--DORygI_ZabM-BIl3UAAM',
    appId: '1:813403601538:ios:a66cc1fee98d5a455b929b',
    messagingSenderId: '813403601538',
    projectId: 'shawan-app',
    storageBucket: 'shawan-app.firebasestorage.app',
    iosBundleId: 'com.example.shawanApp',
  );
}
